### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by ghost** [Sergeon/php-hashcash-implementation#1]
Hello, What is "$ puzzle = Model_Puzzle :: forge () ;" in Hashcash_Puzzler.php, where to find this class?
Give me more information, thankyou!

**Comment by Sergeon** [comment]
Hi Fabio, I'm glad this repo piqued your interest.

Keep in mind I made this purely as an example: was intended to be part of a code showcase or portfolio, not to be used for real. Also I made it when I was not that experienced.

Now, the `Model_Puzzle` class is a placeholder for the class that would interact with the database. It is not a real class in the repo as you say.

Since this is a pretty simple example, I didn't add any kind of database configuration. I'm just assuming that, should this code be used for real, `Model_Puzzle` would be a class that interacts with a database's `puzzle` table. 

I think at the time I chose those syntax after laravel's eloquent or maybe the FuelPHP ORM, I cannot remember. However,  it is just an example. I maybe should've just write a comment instead of adding a non-working line.

As I said in a comment in [the hashcash.php file](https://github.com/Sergeon/php-hashcash-implementation/blob/master/hashcash.php), the system should store the puzzles so no puzzle is used more than once, that was the reason to add that `Model_Puzzle` class as a placeholder.

The idea is that a user, with no authentication, asks for a puzzle on the wild: we don't know who they are nor we don't care. We respond with a puzzle and forgot about them. Some time later, we receive a request with a puzzle solution trying to perform an action in our system.

So if we  only check that the nonce is valid, that user can use that same nonce and puzzle again and again and we cannot track that they aren't really making any new computation. Therefore, we must store the puzzles in our database and check that a single puzzle is used only once.

 Now I see I should've more clear about that. Maybe I will spare some quarantine time to improve the repo.

Thanks for pointing that out!
